# New Label 

Cách 2: 
- nhóm Intermediate: bethesda 1, 3, và 4; 
- nhóm high probability of benign (HPB): bethesda 2; 
- nhóm high probability of malignant (HPM): bethesda 5 và 6

# PREPARE CSV FILE

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../metadata/TAN_patient_dataset.csv',index_col=0)
df1 = pd.read_csv('../metadata/TAN_image_path.csv',index_col=0)

In [3]:
df

,Scan ID,Cytology no.,Diagnosis/Bethesda system,Bethesda actual,Histopathology,Present,Present (Manual),label,fold_0,fold_1,fold_2,fold_3,fold_4,patient_id
0,TAN001,C-11-22,Malignant,5,Anaplastic carcinoma,1,exist,2,test,train,train,train,train,1
1,TAN002,C-20-22,Benign nodule,1,Simple Nodular Goitre,1,exist,1,train,train,test,train,train,2
2,TAN003,C-53-23,Benign nodule,1,Simple Nodular Goitre,1,exist,1,train,train,test,train,train,3
3,TAN004,C-36-23,Benign nodule,1,Simple Nodular Goitre,1,exist,1,train,train,train,train,train,4
4,TAN005,C-373-20,Benign nodule,1,Simple Nodular Goitre,1,exist,1,train,test,test,train,train,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,TAN101,C-076-23,Carcinoma,5,No biopsy,1,exist,2,train,train,train,train,train,101
101,TAN102,C-285-23,Goitre/thyroiditis,1,Cystic goitre,1,exist,1,train,train,train,train,train,102
102,TAN103,CP-01-23,Carcinoma,5,Anaplastic carcinoma,1,exist,2,train,train,train,train,train,103
103,TAN104,C-302-23,Colloid goitre,1,Colloid goitre,1,exist,1,train,train,train,train,test,104
104,TAN105,C-329-23,Follicular neoplasm,3,Follicular adenoma,1,exist,0,train,train,test,train,train,105

In [4]:
df1

      patient_id                                         image_path
0             97  ../data/Tanzania-Data/TAN097/IMG_2301251206156...
1             97  ../data/Tanzania-Data/TAN097/IMG_2301251202141...
2             97  ../data/Tanzania-Data/TAN097/IMG_2301251158260...
3             97  ../data/Tanzania-Data/TAN097/IMG_2301251200592...
4             97  ../data/Tanzania-Data/TAN097/IMG_2301251204265...
...          ...                                                ...
1192         101  ../data/Tanzania-Data/TAN101/IMG_2302021504226...
1193         101  ../data/Tanzania-Data/TAN101/IMG_2302021458365...
1194         101  ../data/Tanzania-Data/TAN101/IMG_2302021505018...
1195         101  ../data/Tanzania-Data/TAN101/IMG_2302021505310...
1196         101  ../data/Tanzania-Data/TAN101/IMG_2302021453508...

[1197 rows x 2 columns]

In [5]:
df = df.merge(df1, how='inner', left_on='patient_id', right_on='patient_id')
df

,Scan ID,Cytology no.,Diagnosis/Bethesda system,Bethesda actual,Histopathology,Present,Present (Manual),label,fold_0,fold_1,fold_2,fold_3,fold_4,patient_id,image_path
0,TAN001,C-11-22,Malignant,5,Anaplastic carcinoma,1,exist,2,test,train,train,train,train,1,../data/Tanzania-Data/TAN001/IMG_20220623_1400...
1,TAN001,C-11-22,Malignant,5,Anaplastic carcinoma,1,exist,2,test,train,train,train,train,1,../data/Tanzania-Data/TAN001/IMG_20220623_1413...
2,TAN001,C-11-22,Malignant,5,Anaplastic carcinoma,1,exist,2,test,train,train,train,train,1,../data/Tanzania-Data/TAN001/IMG_20220623_1349...
3,TAN001,C-11-22,Malignant,5,Anaplastic carcinoma,1,exist,2,test,train,train,train,train,1,../data/Tanzania-Data/TAN001/IMG_20220623_1349...
4,TAN001,C-11-22,Malignant,5,Anaplastic carcinoma,1,exist,2,test,train,train,train,train,1,../data/Tanzania-Data/TAN001/IMG_20220623_1413...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1192,TAN105,C-329-23,Follicular neoplasm,3,Follicular adenoma,1,exist,0,train,train,test,train,train,105,../data/Tanzania-Data/TAN105/IMG_2303311302112...
1193,TAN105,C-329-23,Follicular neoplasm,3,Follicular adenoma,1,exist,0,train,train,test,train,train,105,../data/Tanzania-Data/TAN105/IMG_2303311304087...
1194,TAN105,C-329-23,Follicular neoplasm,3,Follicular adenoma,1,exist,0,train,train,test,train,train,105,../data/Tanzania-Data/TAN105/IMG_2303311305261...
1195,TAN105,C-329-23,Follicular neoplasm,3,Follicular adenoma,1,exist,0,train,train,test,train,train,105,../data/Tanzania-Data/TAN105/IMG_2303311306152...
1196,TAN105,C-329-23,Follicular neoplasm,3,Follicular adenoma,1,exist,0,train,train,test,train,train,105,../data/Tanzania-Data/TAN105/IMG_2303311304362...

In [6]:
df[['patient_id', 'label']].drop_duplicates()['label'].value_counts().sort_index()

label
0    14
1    68
2    13
Name: count, dtype: int64

In [7]:
df['new_label'] = df['label']
df

,Scan ID,Cytology no.,Diagnosis/Bethesda system,Bethesda actual,Histopathology,Present,Present (Manual),label,fold_0,fold_1,fold_2,fold_3,fold_4,patient_id,image_path,new_label
0,TAN001,C-11-22,Malignant,5,Anaplastic carcinoma,1,exist,2,test,train,train,train,train,1,../data/Tanzania-Data/TAN001/IMG_20220623_1400...,2
1,TAN001,C-11-22,Malignant,5,Anaplastic carcinoma,1,exist,2,test,train,train,train,train,1,../data/Tanzania-Data/TAN001/IMG_20220623_1413...,2
2,TAN001,C-11-22,Malignant,5,Anaplastic carcinoma,1,exist,2,test,train,train,train,train,1,../data/Tanzania-Data/TAN001/IMG_20220623_1349...,2
3,TAN001,C-11-22,Malignant,5,Anaplastic carcinoma,1,exist,2,test,train,train,train,train,1,../data/Tanzania-Data/TAN001/IMG_20220623_1349...,2
4,TAN001,C-11-22,Malignant,5,Anaplastic carcinoma,1,exist,2,test,train,train,train,train,1,../data/Tanzania-Data/TAN001/IMG_20220623_1413...,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1192,TAN105,C-329-23,Follicular neoplasm,3,Follicular adenoma,1,exist,0,train,train,test,train,train,105,../data/Tanzania-Data/TAN105/IMG_2303311302112...,0
1193,TAN105,C-329-23,Follicular neoplasm,3,Follicular adenoma,1,exist,0,train,train,test,train,train,105,../data/Tanzania-Data/TAN105/IMG_2303311304087...,0
1194,TAN105,C-329-23,Follicular neoplasm,3,Follicular adenoma,1,exist,0,train,train,test,train,train,105,../data/Tanzania-Data/TAN105/IMG_2303311305261...,0
1195,TAN105,C-329-23,Follicular neoplasm,3,Follicular adenoma,1,exist,0,train,train,test,train,train,105,../data/Tanzania-Data/TAN105/IMG_2303311306152...,0
1196,TAN105,C-329-23,Follicular neoplasm,3,Follicular adenoma,1,exist,0,train,train,test,train,train,105,../data/Tanzania-Data/TAN105/IMG_2303311304362...,0

In [8]:
df[['patient_id', 'new_label']].drop_duplicates()['new_label'].value_counts().sort_index()

new_label
0    14
1    68
2    13
Name: count, dtype: int64

In [9]:
df.to_csv('../metadata/TAN_opt2_3c.csv')