In [1]:
import pandas as pd
import os
import shutil

In [2]:
LOC = '../data/huggingface_NOH'

In [3]:
df = pd.read_csv('../metadata/image_dataset_v2.csv', index_col=0)
df['unique_img_id'] = df['data'] + '__' + df['patient_id'] + '__' + df['label'].astype(str) + '__' + df['filename']
df

,data,patient_id,img_id,label,dataset,img_path,filename,new_img_path,unique_img_id
0,TAN,TAN045,TAN_TAN045,1,train,/content/drive/MyDrive/Colab Notebooks/AI4Thyr...,1672994795748.jpg,processed_img/TAN_TAN045/1672994795748.jpg,TAN__TAN045__1__1672994795748.jpg
1,TAN,TAN045,TAN_TAN045,1,train,/content/drive/MyDrive/Colab Notebooks/AI4Thyr...,1672994795743.jpg,processed_img/TAN_TAN045/1672994795743.jpg,TAN__TAN045__1__1672994795743.jpg
2,TAN,TAN045,TAN_TAN045,1,train,/content/drive/MyDrive/Colab Notebooks/AI4Thyr...,1672994795718.jpg,processed_img/TAN_TAN045/1672994795718.jpg,TAN__TAN045__1__1672994795718.jpg
3,TAN,TAN045,TAN_TAN045,1,train,/content/drive/MyDrive/Colab Notebooks/AI4Thyr...,1672994795729.jpg,processed_img/TAN_TAN045/1672994795729.jpg,TAN__TAN045__1__1672994795729.jpg
4,TAN,TAN045,TAN_TAN045,1,train,/content/drive/MyDrive/Colab Notebooks/AI4Thyr...,1672994795723.jpg,processed_img/TAN_TAN045/1672994795723.jpg,TAN__TAN045__1__1672994795723.jpg
...,...,...,...,...,...,...,...,...,...
3350,TAN,TAN014,TAN_TAN014,1,test,/content/drive/MyDrive/Colab Notebooks/AI4Thyr...,IMG_221006113544221.jpg,processed_img/TAN_TAN014/IMG_221006113544221.jpg,TAN__TAN014__1__IMG_221006113544221.jpg
3351,TAN,TAN014,TAN_TAN014,1,test,/content/drive/MyDrive/Colab Notebooks/AI4Thyr...,IMG_221006113944682.jpg,processed_img/TAN_TAN014/IMG_221006113944682.jpg,TAN__TAN014__1__IMG_221006113944682.jpg
3352,TAN,TAN014,TAN_TAN014,1,test,/content/drive/MyDrive/Colab Notebooks/AI4Thyr...,IMG_221006113632001.jpg,processed_img/TAN_TAN014/IMG_221006113632001.jpg,TAN__TAN014__1__IMG_221006113632001.jpg
3353,TAN,TAN014,TAN_TAN014,1,test,/content/drive/MyDrive/Colab Notebooks/AI4Thyr...,IMG_221006113754747.jpg,processed_img/TAN_TAN014/IMG_221006113754747.jpg,TAN__TAN014__1__IMG_221006113754747.jpg
3354,TAN,TAN014,TAN_TAN014,1,test,/content/drive/MyDrive/Colab Notebooks/AI4Thyr...,IMG_221006113833108.jpg,processed_img/TAN_TAN014/IMG_221006113833108.jpg,TAN__TAN014__1__IMG_221006113833108.jpg

In [4]:
df=df[df['data']=='NOH'].reset_index(drop=True)
df

,data,patient_id,img_id,label,dataset,img_path,filename,new_img_path,unique_img_id
0,NOH,122,NOH_122,4,train,/content/drive/MyDrive/Colab Notebooks/AI4Thyr...,IMG_20230228_082014.jpg,processed_img/NOH_122/IMG_20230228_082014.jpg,NOH__122__4__IMG_20230228_082014.jpg
1,NOH,122,NOH_122,4,train,/content/drive/MyDrive/Colab Notebooks/AI4Thyr...,IMG_20230228_082225.jpg,processed_img/NOH_122/IMG_20230228_082225.jpg,NOH__122__4__IMG_20230228_082225.jpg
2,NOH,122,NOH_122,4,train,/content/drive/MyDrive/Colab Notebooks/AI4Thyr...,IMG_20230228_082229.jpg,processed_img/NOH_122/IMG_20230228_082229.jpg,NOH__122__4__IMG_20230228_082229.jpg
3,NOH,122,NOH_122,4,train,/content/drive/MyDrive/Colab Notebooks/AI4Thyr...,IMG_20230228_081641.jpg,processed_img/NOH_122/IMG_20230228_081641.jpg,NOH__122__4__IMG_20230228_081641.jpg
4,NOH,122,NOH_122,4,train,/content/drive/MyDrive/Colab Notebooks/AI4Thyr...,IMG_20230228_082243.jpg,processed_img/NOH_122/IMG_20230228_082243.jpg,NOH__122__4__IMG_20230228_082243.jpg
...,...,...,...,...,...,...,...,...,...
2043,NOH,24,NOH_24,5,test,/content/drive/MyDrive/Colab Notebooks/AI4Thyr...,IMG_20230116_082639.jpg,processed_img/NOH_24/IMG_20230116_082639.jpg,NOH__24__5__IMG_20230116_082639.jpg
2044,NOH,24,NOH_24,5,test,/content/drive/MyDrive/Colab Notebooks/AI4Thyr...,IMG_20230116_082508.jpg,processed_img/NOH_24/IMG_20230116_082508.jpg,NOH__24__5__IMG_20230116_082508.jpg
2045,NOH,24,NOH_24,5,test,/content/drive/MyDrive/Colab Notebooks/AI4Thyr...,IMG_20230116_082541.jpg,processed_img/NOH_24/IMG_20230116_082541.jpg,NOH__24__5__IMG_20230116_082541.jpg
2046,NOH,24,NOH_24,5,test,/content/drive/MyDrive/Colab Notebooks/AI4Thyr...,IMG_20230116_082615.jpg,processed_img/NOH_24/IMG_20230116_082615.jpg,NOH__24__5__IMG_20230116_082615.jpg
2047,NOH,24,NOH_24,5,test,/content/drive/MyDrive/Colab Notebooks/AI4Thyr...,IMG_20230116_082550.jpg,processed_img/NOH_24/IMG_20230116_082550.jpg,NOH__24__5__IMG_20230116_082550.jpg

In [5]:
os.makedirs(LOC, exist_ok=True)

In [6]:
gs = df.groupby(['dataset','label'])

In [7]:
for i, g in gs:
    cur_folder = os.path.join(LOC, i[0], str(i[1]))
    os.makedirs(cur_folder, exist_ok=True)
    for _, r in g.iterrows():
        src_path = os.path.join('data', r['new_img_path'])
        dst_path = os.path.join(cur_folder, r['unique_img_id'])
        shutil.copy(src_path, dst_path)